services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  wbot:
    build:
      context: .
    volumes:
      - .wwebjs_auth/:/app/.wwebjs_auth/
      - ./videos/:/app/videos/
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
